language: node_js
node_js:
- '8'
cache:
  directories:
  - node_modules
branches:
  only:
  - master
before_install:
- openssl aes-256-cbc -K $encrypted_85f34c22de98_key -iv $encrypted_85f34c22de98_iv
  -in id_rsa.enc -out ~/.ssh/id_rsa -d
- chmod 600 ~/.ssh/id_rsa
# - echo -e "Host 47.99.102.212\n\tStrictHostKeyChecking no\n" >> ~/.ssh/config
install:
- npm install
- npm run build
- npm run start
# - npm run generate
script:
- echo "Skipping tests"
addons:
  ssh_known_hosts: 47.99.102.212
after_success:
# - rsync -az --delete ./dist/* root@47.99.102.212:/data/html/nuxt # copy dist文件夹下的所有文件
- ssh root@47.99.102.212 'cd /data/ssr && git pull && export PATH=/root/nvm/versions/node/v10.15.1/bin:$PATH && npm install && npm run build && npm run start'
