language: node_js
node_js:
- '8'
cache:
  directories:
  - node_modules
branches:
  only:
  - master
before_install:
- openssl aes-256-cbc -K $encrypted_85f34c22de98_key -iv $encrypted_85f34c22de98_iv
  -in id_rsa.enc -out ~/.ssh/id_rsa -d
- chmod 600 ~/.ssh/id_rsa
- echo -e "Host 47.99.102.212\n\tStrictHostKeyChecking no\n" >> ~/.ssh/config
install:
- npm install
- npm run generate
script:
- echo "Skipping tests"
addons:
  ssh_known_hosts: 47.99.102.212
after_success:
# - ssh root@47.99.102.212 -o StrictHostKeyChecking=no 'cd /data/html/nuxt && git pull
#   && npm run generate'
- npm prune --production  # 删除devDependencies
- tar -jcf test.bz2 *    # 打包并压缩代码
- scp test.bz2 root@47.99.102.212:~/data/html/  # 复制到生产服务器上
- ssh root@47.99.102.212 'mkdir -p test && tar -jxf test.tar.bz2 -C test' # 解压